//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codename.FileSyncChecker.XProvider.ResourceValue.MainFrame {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlValue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlValue() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codename.FileSyncChecker.XProvider.ResourceValue.MainFrame.ControlValue", typeof(ControlValue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnAllClear {
            get {
                return ResourceManager.GetString("btnAllClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnStartFileHashCheck {
            get {
                return ResourceManager.GetString("btnStartFileHashCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일싱크 맞춤과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnStartFileSync {
            get {
                return ResourceManager.GetString("btnStartFileSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업중단과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnStartFileXCommand_StopWorking {
            get {
                return ResourceManager.GetString("btnStartFileXCommand_StopWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   싱크파일 복사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnStartGetSyncFile {
            get {
                return ResourceManager.GetString("btnStartGetSyncFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   왼쪽 -&gt; 오른쪽과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string cbWorkDirectoryPosition_LeftRight {
            get {
                return ResourceManager.GetString("cbWorkDirectoryPosition_LeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string cbWorkDirectoryPosition_None {
            get {
                return ResourceManager.GetString("cbWorkDirectoryPosition_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오른쪽 -&gt; 왼쪽과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string cbWorkDirectoryPosition_RightLeft {
            get {
                return ResourceManager.GetString("cbWorkDirectoryPosition_RightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string gbControlBox {
            get {
                return ResourceManager.GetString("gbControlBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   왼쪽과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblLeftDirectory {
            get {
                return ResourceManager.GetString("lblLeftDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오른쪽과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblRightDirectory {
            get {
                return ResourceManager.GetString("lblRightDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일싱크체크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainFrame {
            get {
                return ResourceManager.GetString("MainFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon MainFrame_Icon {
            get {
                object obj = ResourceManager.GetObject("MainFrame_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   양쪽에 존재과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tpMatchPartTab {
            get {
                return ResourceManager.GetString("tpMatchPartTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   왼쪽에만 존재과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tpOnlyLeftPartTab {
            get {
                return ResourceManager.GetString("tpOnlyLeftPartTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오른쪽에만 존재과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tpOnlyRightPartTab {
            get {
                return ResourceManager.GetString("tpOnlyRightPartTab", resourceCulture);
            }
        }
    }
}
