//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codename.FileSyncChecker.XProvider.ResourceValue.MainFrame {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkMessageValue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkMessageValue() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codename.FileSyncChecker.XProvider.ResourceValue.MainFrame.WorkMessageValue", typeof(WorkMessageValue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   작업을 종료하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllEndFileSyncCommand {
            get {
                return ResourceManager.GetString("AllEndFileSyncCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일의 변경사항이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllMatchFileHashItem {
            get {
                return ResourceManager.GetString("AllMatchFileHashItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   싱크파일 복사 디렉토리가 작업 디렉토리와 동일하거나
        ///하위 디렉토리입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyDirWorkDirMatchOrSub {
            get {
                return ResourceManager.GetString("CopyDirWorkDirMatchOrSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리스트를 구성중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateWorkItemList {
            get {
                return ResourceManager.GetString("CreateWorkItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리스트에 항목이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EmptyFileHashItemList {
            get {
                return ResourceManager.GetString("EmptyFileHashItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   디렉토리 경로가 변경됨으로 인해 초기화됩니다. (데이터 무결성 위반)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EndDataIntegrity {
            get {
                return ResourceManager.GetString("EndDataIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일싱크 맞춤작업은
        ///선택된 위치에 따라서 파일복사 및 덮어쓰기, 삭제가 발생합니다.
        ///
        ///파일의 싱크를 맞추겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExecuteConfirm_FileSync {
            get {
                return ResourceManager.GetString("ExecuteConfirm_FileSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   싱크파일 복사작업은
        ///선택된 위치에 따라 복사되는 파일 및 덮어쓰기 파일이
        ///앞서 지정된 디렉토리(*1)에 복사됩니다.
        ///(*1 : {0})
        ///
        ///싱크파일을 복사하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExecuteConfirm_GetSyncFile {
            get {
                return ResourceManager.GetString("ExecuteConfirm_GetSyncFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExitApplicationConfirm {
            get {
                return ResourceManager.GetString("ExitApplicationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 디렉토리가 동일하거나 하위 디렉토리는 허용하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchOrSubWorkDirectory {
            get {
                return ResourceManager.GetString("MatchOrSubWorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   싱크파일 복사를 위한 디렉토리가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotExistCopyDirectory {
            get {
                return ResourceManager.GetString("NotExistCopyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 파라메터 정보가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotExistCoreWorkerOrArgs {
            get {
                return ResourceManager.GetString("NotExistCoreWorkerOrArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 작업 디렉토리가 없거나 올바르지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NowAllowWorkDirectory {
            get {
                return ResourceManager.GetString("NowAllowWorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   준비됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NowReady {
            get {
                return ResourceManager.GetString("NowReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 작업중으로 프로그램을 종료할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NowWoringExitApplication {
            get {
                return ResourceManager.GetString("NowWoringExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업중입니다. 기다려주세요...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NowWorking {
            get {
                return ResourceManager.GetString("NowWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   싱크를 위한 디렉토리 위치를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseSelectSyncPosition {
            get {
                return ResourceManager.GetString("PleaseSelectSyncPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업을 중단하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StopWorking {
            get {
                return ResourceManager.GetString("StopWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 작업이 종료된 후 다시 시도하여주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 파라메터의 리스트 갯수와 현재 데이터 리스트의 갯수가 다릅니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnMatchArgsListItemCount {
            get {
                return ResourceManager.GetString("UnMatchArgsListItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업 파라메터의 작업경로와 선택된 작업경로가 다릅니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnMatchArgsWorkDirectory {
            get {
                return ResourceManager.GetString("UnMatchArgsWorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지정되지 않은 파일작업 명령입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnSetWorkCommand {
            get {
                return ResourceManager.GetString("UnSetWorkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 작업의 선택이 준비되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WorkEndReadyNextWork {
            get {
                return ResourceManager.GetString("WorkEndReadyNextWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업이 중단되었으며, 새로운 작업의 진행이 준비되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WorkStopPleaseNewWork {
            get {
                return ResourceManager.GetString("WorkStopPleaseNewWork", resourceCulture);
            }
        }
    }
}
